- CHANGELOG.md
- sdk-media-webrtc/api/sdk-media-webrtc.api
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
This change should help bridge the already-available implementations of
`VideoCapturer` and `LocalVideoTrack` provided by the SDK.
> feat: add a way to create LocalVideoTracks from VideoCapturers

- CHANGELOG.md
- sdk-catalog/build.gradle.kts
Specifically, `pexipSdk.media.android` was missing.
> fix(catalog): ensure that version catalog contains all relevant modules

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
Sets up Snyk to `test` on PRs and `monitor` on merges to `main`.
The plan is to run it for some time, maybe compare with other solutions (e.g. CodeQL).
> ci: setup snyk

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
`snyk/actions/gradle-jdk11` started to fail after upgrading to Gradle 8. Migrating to `snyk/actions/setup` seems to fix that.
> ci: switch to snyk/actions/setup

- .github/dependabot.yml
It appears that Dependabot doesn't take repositories specified in
`settings.gradle.kts` into account and we're not notified of
Android dependency updates.
https://github.com/dependabot/dependabot-core/issues/3286
> ci: manually specify google maven repo

- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalVideoTrack.kt
When a client stops capturing, last sent frame will be left lingering in
the conference. While this is not an issue if this change is signalled
via REST API, it affects users in gateway calls where removing from mix
is not supported.
This commit inserts a black frame when `onCapturerStopped()` in invoked.
> fix: insert black frame when VideoCapturer stops

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- .idea/codeStyles/Project.xml
- .idea/kotlinc.xml
- README.md
- plugins/android/build.gradle.kts
- plugins/android/src/main/kotlin/com.pexip.sdk.android.application.gradle.kts
- plugins/android/src/main/kotlin/com.pexip.sdk.android.library.gradle.kts
- plugins/android/src/main/kotlin/com.pexip.sdk.kotlin.android.application.gradle.kts
- plugins/android/src/main/kotlin/com.pexip.sdk.kotlin.android.library.gradle.kts
- plugins/android/src/main/kotlin/internal/Android.kt
- plugins/kotlin/build.gradle.kts
- plugins/kotlin/src/main/kotlin/com.pexip.sdk.kotlin.jvm.gradle.kts
Some of our dependencies (primarily WebRTC) have switched to JDK11, so we also start building with them.
Note that the plugins (and CI) are JDK17 in preparation for AGP 8.0.
> feat: build with jdk11

- sdk-api-infinity/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RealCallStep.kt
It appears that in some scenarios `ack` may take a while to respond,
thus timing out for default OkHttpClient read timeout (10s).
This disables the timeout for `ack` only.
> fix(api): disable read timeout for ack

- CHANGELOG.md
- sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceWorkflow.kt
- sdk-conference-infinity/api/sdk-conference-infinity.api
- sdk-conference-infinity/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Conference.kt
The move is motivated by the following:
1. Modifying `MediaConnectionSignaling` also affects `Conference` API, which often leads to tests not compiling (i.e. if a new method is added)
2. It may prove useful to be able to create new instances of `MediaConnectionSignaling` upon invocation (for scoping purposes)
This is a breaking change and consumers will be unable to compile after the update. The fix is to change `MediaConnectionConfig.Builder(conference)` to `MediaConnectionConfig.Builder(conference.signaling)`.
> refactor(media, conference)!: make MediaConnectionSignaling a property

- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/PeerConnectionWrapper.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalAudioTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalVideoTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcMediaConnection.kt
Note that `PeerConnectionWrapper` now assumes that it will be used from
a single thread and doesn't make any attempts to protect a handful of
properties from concurrent access.
> fix(media): pin MediaConnectionFactory-produced objects to a single thread

- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalAudioTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalVideoTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcMediaConnection.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcVideoTrack.kt
This should additionally fix a rather rare, but still annoying crash when a `Renderer` is being removed, but the underlying `VideoTrack` was already disposed.
Unlike other methods in `MediaStreamTrack`, [`removeSink`](https://webrtc.googlesource.com/src/+/refs/heads/main/sdk/android/api/org/webrtc/VideoTrack.java#49) does not check if the `VideoTrack` still exists and attempts to remove and free `VideoSink` through JNI, which happily blows up (after all, the `VideoTrack` has already been disposed).
> fix(media): switch Executors with CoroutineScopes

- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalAudioTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalVideoTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcMediaConnection.kt
Instead of making sure all the children complete before `dispose()` is called, we'll instead cancel their parent `Job`.
> refactor(media): share a parent Job between children of MediaConnectionFactory

- sdk-api-infinity/api/sdk-api-infinity.api
- sdk-api-infinity/src/main/kotlin/com/pexip/sdk/api/infinity/RequestTokenRequest.kt
- sdk-api-infinity/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RealConferenceStep.kt
- sdk-api-infinity/src/test/kotlin/com/pexip/sdk/api/infinity/ConferenceStepTest.kt
- sdk-api-infinity/src/test/kotlin/com/pexip/sdk/api/infinity/Util.kt
To exchange a registration token for conference token we must use a this header instead of `token`.
> feat(api): add RequestTokenRequest.registrationToken

- sdk-media-webrtc-compose/api/sdk-media-webrtc-compose.api
- sdk-media-webrtc-compose/src/main/kotlin/com/pexip/sdk/media/webrtc/compose/VideoTrackRenderer.kt
The `keepScreenOn` inside AndroidView is not working for me, neither in the SampleApp or in the apps using the SDK. So I moved it to a disposableEffect instead, which seems to work fine.
> fix(media): moved keepScreenOn outside of renderer

- plugins/convention/src/main/kotlin/com/pexip/sdk/internal/Android.kt
`targetSdk` will be bumped a bit later (only affects the sample app) as it requires a few `Service`-related changes.
> feat: bump compileSdk to 34

- .github/workflows/main.yml
- ci: do not upload snyk sarif output
- ci: enable dependency graph in gradle build action
> ci: enable dependency graph in Gradle build action

- sdk-api-infinity/src/main/kotlin/com/pexip/sdk/api/infinity/internal/UnboxingSerializer.kt
- sdk-api-infinity/src/main/kotlin/com/pexip/sdk/api/infinity/internal/UpdateResponseSerializer.kt
- sdk-api-infinity/src/test/kotlin/com/pexip/sdk/api/infinity/internal/UpdateResponseSerializerTest.kt
- sdk-api-infinity/src/test/resources/update_response.json
- sdk-api-infinity/src/test/resources/update_response_direct_media.json
It appears that a transcoded call response contains SDP as a plain String, while direct media call includes a JSON object instead.
> fix(api): handle a different update response form for direct media

- sdk-conference-infinity/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference-infinity/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/ConferenceEvent.kt
- sdk-conference-infinity/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/Events.kt
- sdk-conference-infinity/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/ConferenceEventTest.kt
- sdk-conference-infinity/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/EventsTest.kt
We'll need to pass a few things down through signaling instead, and this will remove the need to have additional `ConferenceEvent`s
> refactor(conference): use raw events and map later

- sdk-api-infinity/api/sdk-api-infinity.api
- sdk-api-infinity/src/main/kotlin/com/pexip/sdk/api/infinity/RequestTokenResponse.kt
- sdk-api-infinity/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ConferenceStepImpl.kt
- sdk-api-infinity/src/main/kotlin/com/pexip/sdk/api/infinity/internal/Util.kt
- sdk-api-infinity/src/test/kotlin/com/pexip/sdk/api/infinity/ConferenceStepTest.kt
- sdk-conference-infinity/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference-infinity/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RefererImpl.kt
- sdk-conference-infinity/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RefererTest.kt
This is a trick to avoid callers of `Referer.refer()` of passing `directMedia`. Instead it uses the value that the original request had.
> feat(api,conference): add directMediaRequested property

- build.gradle.kts
- gradle/libs.versions.toml
- sample/build.gradle.kts
Some issues with Dagger not picking up Wire-generated classes after update to Kotlin 1.9.2x
> refactor: switch back to kapt

- plugins/convention/src/main/kotlin/com/pexip/sdk/KotlinDokkaPlugin.kt
- sdk-media/src/main/kotlin/com/pexip/sdk/media/AudioDeviceManager.kt
- sdk-media/src/test/kotlin/Samples.kt
Run `dokka` to generate the website and see the improved docs.
> docs(media): add a sample for simple AudioDeviceManager usage

- sample/src/main/AndroidManifest.xml
- sample/src/main/kotlin/com/pexip/sdk/sample/SampleWorkflow.kt
- sdk-media-android/src/main/AndroidManifest.xml
- sdk-media-android/src/main/kotlin/com/pexip/sdk/media/android/internal/BluetoothHeadsetObserver.kt
`AudioManager.setCommunicationDevice()` seems to be handling most of the work and does not require this permission to connect and use a Bluetooth headset.
> refactor(media): do not require BLUETOOTH_CONNECT permission

- CHANGELOG.md
- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/Event.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/InfinityService.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/LayoutId.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/RequestedLayout.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/Screen.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/AvailableLayoutsSerializer.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ConferenceStepImpl.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ConferenceStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/internal/EventTest.kt
- sdk-api/src/test/resources/layout.json
- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Layout.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/LayoutId.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Theme.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/TestConferenceStep.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImplTest.kt
This should provide read-only access to currently active layout of the conference.
Ability to transform the layout will come at a later stage.
> feat(conference): add Theme.layout

- CHANGELOG.md
- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/IllegalLayoutTransformException.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ConferenceStepImpl.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ConferenceStepTest.kt
- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Theme.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/TransformLayoutException.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImplTest.kt
- sdk-infinity/api/sdk-infinity.api
This also renames `host_layout` to `layout` (since they are aliases) to better indicate that `host_layout`/`layout` alter the layout for guests in non-Virtual Auditorium calls.
> feat(conference): add a way to transform layout

- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/ParticipantResponse.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ParticipantResponseSerializer.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Participant.kt
There are some cases when it can be `null` in the payload, namely when dialing a user on Pexip Service. This may potentially be true other dialing scenarios.
> fix(conference)!: make Participant.startTime nullable

- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImpl.kt
The role requirement may be relaxed in the future, but consumers should keep in mind that an empty list is possible and handle their UI accordingly.
> fix(conference): do not retry available_layouts and layout_svgs on 403

- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Roster.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImplTest.kt
This points to *your* participant object in the conference and will be useful for getting things like current "hand" state (whether raised or not), etc.
> feat(conference): add Roster.me

- sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceWorkflow.kt
- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Roster.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
This property can be used as a more reliable replacement for `PresentationStartConferenceEvent` and `PresentationStopConferenceEvent`.
> feat(conference): add Roster.presenter

- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImpl.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/Util.kt
Prior approach still had some issues with `layout` event and API participants.
> fix(conference): use debounce for event subscription

- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/Event.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/internal/EventTest.kt
- sdk-api/src/test/resources/layout_direct_media.json
- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Layout.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImplTest.kt
It's not present in direct media `layout` event and causes some issues in direct media calls.
> fix(api)!: make RequestedLayout nullable

- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/MuteException.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Roster.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/UnmuteException.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImplTest.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/TestParticipantStep.kt
Additionally, make every property and method in `Roster` have a default implementation that throws `NotImplementedError` to ensure binary compatibility for the consumers and to avoid breaking them (mostly their tests, really) on version upgrades.
> feat(conference): add mute and unmute to Roster

- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-registration/src/main/kotlin/com/pexip/sdk/registration/infinity/InfinityRegistration.kt
Ideally we should get rid of `java.net.URL` and other `java.*` imports.
> chore(conference,registration): deprecate create that accepts java.net.URL

- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/CallStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ConferenceStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ParticipantStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RegistrationStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/Util.kt
This is required for smooth migration to 5.0.0.
> fix(api): remove usage of okhttp3.internal.*

- .idea/.gitignore
- gradle/libs.versions.toml
- sample/src/main/kotlin/com/pexip/sdk/sample/di/NetworkModule.kt
- sample/src/main/kotlin/com/pexip/sdk/sample/pinrequirement/PinRequirementWorkflow.kt
- sdk-api/api/sdk-api.api
- sdk-api/build.gradle.kts
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/InfinityService.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/NodeResolver.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/CallStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ConferenceStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/InfinityServiceImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ParticipantStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RealNodeResolver.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RegistrationStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RequestBuilderImpl.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/CallStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ConferenceStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/NodeResolverTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ParticipantStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/RegistrationStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/RequestBuilderTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/SecureMockWebServerRule.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/Util.kt
- sdk-infinity/api/sdk-infinity.api
- sdk-infinity/build.gradle.kts
- sdk-infinity/src/commonMain/kotlin/com/pexip/sdk/infinity/Node.kt
- sdk-infinity/src/commonMain/kotlin/com/pexip/sdk/infinity/NodeResolver.kt
- sdk-infinity/src/commonTest/kotlin/com/pexip/sdk/infinity/NodeResolverTest.kt
- sdk-infinity/src/jvmMain/kotlin/com/pexip/sdk/infinity/NodeResolver.jvm.kt
This PR adds a `Node` that represents the address of the Infinity node
that the SDK will communicate with.
Note that while the `Node` includes `port`, in real world use it will
almost exclusively be 443 since Infinity forces you to use TLS over said
port. It's exposed here to allow testing against `MockWebServer`.
We also added a suspending `NodeResolver` that will return a `Node`
list and deprecated the one found in `:sdk-api` module.
> feat(infinity): introduce Node

- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/InfinityService.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/CallStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RegistrationStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RequestBuilderImpl.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/CallStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ConferenceStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/DtmfRequestTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/NodeResolverTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ParticipantStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/RegistrationStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/RequestBuilderTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/Util.kt
As a bonus, remove most uses of `kotlin.test.assertEquals` (and others)
in favor of `assertk.*`.
> feat(api): add parameters used to create steps to instances

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
We're mostly interested in checking the what we include as a dependency
in the released artifacts, a bit less so when it comes to tooling.
Note the switch to `snyk-linux` instead of `snyk` - it appears that there's an `eval` call that strips the first `'` symbol from the regex, causing the command to fail. Invoking `snyk-linux` directly does the trick, but will cause an error if we were to migrate to a macOS runner.
> ci: force snyk to use runtime classpath

- .github/workflows/main.yml
Some issues with `$(git branch --show-current)` in the CI,
`GITHUB_REF_NAME` gives us the same output.
> ci(snyk): use GITHUB_REF_NAME for target-reference

- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/RequestTokenResponse.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ConferenceStepTest.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
In certain situations a `RequestTokenResponse` may contain a
`parent_participant_uuid` field which is effectively the participant we'd
like to represent and make calls on behalf of.
> feat(api,conference): respect parent_participant_uuid

- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImplTest.kt
The previous implementation ended up causing more issues and overall introduced several other bugs.
The main culprit was found when testing a call scenario where the participant had a role of `guest`. Under these circumstances, a child participanat token cannot perform any actions on the parent participant (even though they're effectively the same), resulting in most calls either failing with proper HTTP response or in some cases emitting 200 without modifying state.
This PR flips things a bit and make all calls via child participant with an appropriate token, but uses parent participant to identify _self_ in the roster. This is necessary since child participant does not participate in populating the roster, only their parent does.
To simplify things a bit we switched from lazily creating …
> fix(conference): incorrect use of parentParticipantId

- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Layout.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImplTest.kt
Several versions of Infinity have a bug where `layout` event will not be
emitted under certain circumstances (e.g. joining using SIP Session ID,
API-only participant, etc.).
This workaround emits a fake `layout` event without much set. During
normal operation it will be followed by a real one, overriding the
values. For SIP Session ID flow it will let the `Theme` construct the
`Layout`, albeit in a limited fashion.
> fix(conference): emit a fake LayoutEvent

- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalAudioTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalVideoTrack.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcMediaConnection.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcVideoTrack.kt
This stops the exceptions from API calls during a media connection propagating uncontrollably to the clients and crashing them
> feat(media): handle coroutines exceptions

- plugins/convention/src/main/kotlin/com/pexip/sdk/AndroidApplicationPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/AndroidLibraryPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/internal/Android.kt
- sample/src/main/AndroidManifest.xml
- sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceMediaProjectionService.kt
- sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceWorkflow.kt
- sample/src/main/res/values/strings.xml
`Service.startForeground()` doesn't seem to allow passing multiple
flags in `foregroundServiceType`, so instead a special
`ConferenceMediaProjectionService` is introduced to notify when the
screen is being shared.
> feat: bump targetSdk to 34

- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/InfinityService.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/ParticipantResponse.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ParticipantStepImpl.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ParticipantStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/internal/EventTest.kt
- sdk-api/src/test/resources/participant_create.json
- sdk-api/src/test/resources/participant_create_unknown.json
- sdk-api/src/test/resources/participant_update.json
A new API introduced in v36 that allows a client to signal whether
they're locally muted.
> feat(api): add client_mute, client_unmute and is_client_muted

- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/DurationAsMillisecondsSerializer.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/DurationAsSecondsStringSerializer.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/internal/RequestTokenResponseSerializerTest.kt
- sdk-api/src/test/resources/request_token_v35.json
- sdk-api/src/test/resources/request_token_v36.json
Serializers previously didn't handle duration values that included a
fraction well. This should improve things a bit and not make the
application crash when on v36.
> fix(api): handle nanos and millis better

- .idea/kotlinc.xml
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/MediaConnectionSignalingImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/MediaConnectionSignalingImplTest.kt
- sdk-infinity/api/sdk-infinity.api
- sdk-infinity/src/commonMain/kotlin/com/pexip/sdk/infinity/Infinity.kt
This will correctly update `is_client_muted` on v36 and up, while using
the old `is_muted` on previous Infinity versions.
> feat(conference): call client_mute/client_unmute on v36 for signaling

- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Participant.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImplTest.kt
This adds a property that indicates the current state of
`clientAudioMuted` on a `Participant`.
> feat(conference): add Participant.clientAudioMuted

- sdk-api/api/sdk-api.api
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ConferenceStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/RegistrationStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/internal/RequestTokenResponseSerializerTest.kt
- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/ClientMuteException.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/ClientUnmuteException.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Roster.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/MediaConnectionSignalingImpl.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/MediaConnectionSignalingImplTest.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RefererTest.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImplTest.kt
- sdk-infinity-test/api/sdk-infinity-test.api
- sdk-infinity-test/src/commonMain/kotlin/com/pexip/sdk/infinity/test/Random.kt
- sdk-infinity/api/sdk-infinity.api
- sdk-infinity/src/commonMain/kotlin/com/pexip/sdk/infinity/UnsupportedInfinityException.kt
- sdk-infinity/src/commonMain/kotlin/com/pexip/sdk/infinity/VersionId.kt
- sdk-registration/src/main/kotlin/com/pexip/sdk/registration/infinity/InfinityRegistration.kt
This is only really useful when the media is provided by some other
means (e.g. SIP) and we want to sync local mute state with Infinity.
> feat(conference): add clientMute and clientUnmute to Roster

- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImplTest.kt
- sdk-infinity/api/sdk-infinity.api
- sdk-infinity/src/commonMain/kotlin/com/pexip/sdk/infinity/VersionId.kt
Additionally, use `parentParticipantId` for `mute` and `unmute` at all times.
> feat(conference): use parentParticipantId from v35.1

- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/Event.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/internal/EventTest.kt
- sdk-api/src/test/resources/conference_update.json
- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Roster.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImplTest.kt
This is a new v36 API that allows hosts to forbid guests from unmuting
themselves.
> feat(conference): add a way to observe guestsCanUnmute state

- CHANGELOG.md
- plugins/convention/src/main/kotlin/com/pexip/sdk/AndroidApplicationPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/AndroidLibraryPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/KotlinAndroidLibraryPublishingPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/KotlinJvmPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/KotlinMultiplatformPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/internal/CompileOptions.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/internal/Jvm.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/internal/KotlinTopLevelExtension.kt
This is mostly brought up by updates to WebRTC (required JDK17) and has
been generally supported by Android for some time now.
> feat: set jvm toolchain to 17

- sample/src/main/kotlin/com/pexip/sdk/sample/pinchallenge/PinChallengeWorkflow.kt
- sample/src/main/kotlin/com/pexip/sdk/sample/pinrequirement/PinRequirementWorkflow.kt
- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/Call.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/EventSourceFactory.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/coroutines/CallUtil.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RealCall.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RealNodeResolver.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/CallStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/NodeResolverTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ParticipantStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/RegistrationStepTest.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/RequestBuilderTest.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/Events.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/MediaConnectionSignalingImpl.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/MessengerImpl.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RefererImpl.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/ThemeImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/TestCall.kt
- sdk-registration/src/main/kotlin/com/pexip/sdk/registration/infinity/InfinityRegistration.kt
- sdk-registration/src/main/kotlin/com/pexip/sdk/registration/infinity/internal/Events.kt
- sdk-registration/src/main/kotlin/com/pexip/sdk/registration/infinity/internal/RegisteredDevicesFetcher.kt
- sdk-registration/src/test/kotlin/com/pexip/sdk/registration/infinity/internal/TestCall.kt
This is the first step in a series of PRs that see the deprecation (and
subsequent removal) of blocking and callback style access in `:sdk-api`.
The end goal is to have everything be suspending instead.
> refactor(api): move await to Call, asFlow to EventSourceFactory

- CHANGELOG.md
- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/InfinityService.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/CallStepImpl.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/CallStepTest.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/MediaConnectionSignalingImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/MediaConnectionSignalingImplTest.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcMediaConnection.kt
- sdk-media/api/sdk-media.api
- sdk-media/src/main/kotlin/com/pexip/sdk/media/MediaConnectionSignaling.kt
This is likely to result in 403 since we may release the token around the
same time in a normal call, but it is important for breakout rooms where
the token may live longer than an individual `MediaConnection`.
> feat(api,media): call disconnect when disposing MediaConnection

- .idea/kotlinc.xml
- CHANGELOG.md
- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/InfinityService.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ConferenceStepImpl.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/ConferenceStepTest.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RefererImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RefererTest.kt
This is a direct replacement for `ConferenceStep.requestBuilder.conference()`.
> feat(api): add ConferenceStep.conference()

- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/InfinityService.kt
These properties returned the previous "step" object, but to be able to
reuse some for breakouts we'll have to remove these properties.
> refactor(api): deprecate some InfinityService properties

- CHANGELOG.md
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
There has been a number of reports of hardware NS and AEC not working on
a range of devices.
Instead, we'll use software NS and AEC provided by WebRTC and consumers
can customize this behavior by providing a custom `AudioDeviceModule` if
they wish to use hardware implementation.
> feat(media): use software ns and aec

- sdk-conference/api/sdk-conference.api
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Breakout.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Breakouts.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Conference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/BreakoutImpl.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/BreakoutsImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/BreakoutsImplTest.kt
This PR adds a few new classes and observes any relevant
`breakout_begin` & `breakout_end` events to manage active breakouts.
> feat(conference): add Breakout and Breakouts

- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/InfinityEvent.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/InfinityService.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/ConferenceStepImpl.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RealEventSource.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RealEventSourceFactory.kt
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/internal/RegistrationStepImpl.kt
- sdk-api/src/test/kotlin/com/pexip/sdk/api/infinity/internal/InfinityEventTest.kt
- sdk-api/src/test/resources/incoming.json
- sdk-api/src/test/resources/incoming_cancelled.json
- sdk-api/src/test/resources/refer.json
Previously, we'd use `when (type)` to distinguish between the type of
the incoming event and handle the deserialization manually.
With this change, we switch to generated serializers by creating a
"fake" JSON that wraps `type` and `data`. We use `#event` as the type
discriminator since we know that it will not be included in `data`.
> refactor(api): switch to polymorphic serialization for Event

- CHANGELOG.md
- sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceScreen.kt
- sdk-media-webrtc-compose/api/sdk-media-webrtc-compose.api
- sdk-media-webrtc-compose/src/main/kotlin/com/pexip/sdk/media/webrtc/compose/VideoTrackEmbeddedRenderer.kt
This is a TextureView-based Composable that is embedded directly in the
UI hierarchy.
Unlike `VideoTrackRenderer` effects such as clipping can be safely
applied to this Composable (see the modified self-view for an example of
this).
> feat(media): add VideoTrackEmbeddedRenderer

- CHANGELOG.md
- sdk-api/api/sdk-api.api
- sdk-api/src/main/kotlin/com/pexip/sdk/api/infinity/RequestTokenRequest.kt
This means that consumers should explicitly opt-in to support breakouts
feature. By default, this is not supported and the behavior matches that
of a guest on Infinity v36+.
Note that on v34 and v35 if the participant is being transfered to a
breakout they may not receive `refer` event, which means that they will
stay in the main room.
> feat(api): set breakout_capable to false by default

- sdk-conference/build.gradle.kts
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Breakout.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Breakouts.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/Conference.kt
- sdk-core/api/sdk-core.api
- sdk-core/src/commonMain/kotlin/com/pexip/sdk/core/ExperimentalSdkApi.kt
The feature is not complete and it would help consumers to be aware of
that until the API is stable.
> feat(core,conference): add ExperimentalSdkApi and annotate Breakouts

- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/PeerConnectionWrapper.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcMediaConnection.kt
We now pass a list of `RtpTransceiverKey` that should be added during
object construction instead of waiting and initialiazing them later via
suspending functions.
This should hopefully fix the double main video issue when joining a VMR
where somebody is already sharing a presentation.
> fix(media): avoid racey RtpTransciever initialization

- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/InfinityConference.kt
- sdk-conference/src/main/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImpl.kt
- sdk-conference/src/test/kotlin/com/pexip/sdk/conference/infinity/internal/RosterImplTest.kt
This includes some internal changes so that `clientMute/Unmute` could be
used in `GATEWAY` calls as well.
> feat(conference): provide a better interop for clientMute/Unmute

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- RELEASING.md
- build.gradle.kts
- gradle/libs.versions.toml
- plugins/convention/build.gradle.kts
- plugins/convention/src/main/kotlin/com/pexip/sdk/KotlinAndroidLibraryPublishingPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/KotlinJvmPublishingPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/KotlinMultiplatformPublishingPlugin.kt
- plugins/convention/src/main/kotlin/com/pexip/sdk/PublishingPlugin.kt
- sdk-api/build.gradle.kts
- sdk-catalog/build.gradle.kts
- sdk-conference/build.gradle.kts
- sdk-core/build.gradle.kts
- sdk-infinity-test/build.gradle.kts
- sdk-infinity/build.gradle.kts
- sdk-media-android/build.gradle.kts
- sdk-media-webrtc-compose/build.gradle.kts
- sdk-media-webrtc/build.gradle.kts
- sdk-media/build.gradle.kts
- sdk-registration/build.gradle.kts
This updates the publishing bit to use new Central host instead of the
old s01, which requires a new authentication method and a new plugin.
Note that we also enable auto release here to avoid going to the
dashboard.
> ci: migrate from s01 to central

- CHANGELOG.md
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcMediaConnection.kt
- sdk-media/api/sdk-media.api
- sdk-media/src/main/kotlin/com/pexip/sdk/media/MediaConnectionConfig.kt
The one included in the SDK is pretty basic and may not cover
all the cases, so this gives clients a way to disable it and use their
own logic instead.
> feat(media): add a way to disable built-in mute sync for audio and video

- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/Observer.kt
- sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/PeerConnectionWrapper.kt
ICE candidates that had the same `sdpMid` value were previously skipped when `ContinualGatheringPolicy` was set to `ContinualGatheringPolicy.GATHER_ONCE`(default), leading to potential connectivity issues as the candidates may have different content in the `sdp` itself. This potential fix removes this equality check and ensures that all candidates are signalled to the remote client.
> fix(media): avoid skipping potential ICE candidates
